// Generated by scripts/gen-agent-board.mjs from boards/esp32-devkitc-30.json. Do not edit by hand:
//   node scripts/gen-agent-board.mjs esp32-devkitc-30
// The committed copy is for the ESP32 DevKit, so the sketch also compiles on its own.
// Pin numbers are the ones used in Arduino code (PinDef.gpio in shared/types.ts).
#pragma once

#define BP_BOARD_ID "esp32-devkitc-30"
#define BP_BOARD_FAMILY "esp32"
#define BP_FAMILY_ESP32 1
// Chip name reported by "hello" where the core cannot read it from the chip.
#define BP_CHIP_NAME "ESP32"
// Word used for pin numbers in messages.
#define BP_PIN_NOUN "GPIO"

// ADC: full scale (rules.adcMaxMv) and the resolution the agent reads with.
#define BP_ADC_MAX_MV 3300
#define BP_ADC_BITS 12

// Default I2C pins of the board (used as examples in messages).
#define BP_EXAMPLE_SDA 21
#define BP_EXAMPLE_SCL 22

// Pins on the header, reported by the "pins" command.
#define BP_HEADER_PIN_COUNT 25
#define BP_HEADER_PINS {1, 2, 3, 4, 5, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33, 34, 35, 36, 39}

// Strapping pins, read at boot (none: the boot event has no "strapping" field).
#define BP_STRAP_COUNT 5
#define BP_STRAP_PINS {0, 2, 5, 12, 15}

// Bitmaps over pin numbers 0..BP_GPIO_COUNT-1 (bit g of byte g/8).
#define BP_GPIO_COUNT 40
#define BP_MAP_BYTES 5
// Pins that exist.
#define BP_MAP_VALID {0xFF, 0xFF, 0xEF, 0x0E, 0xFF}
// Wired to the flash: always refused. [6,7,8,9,10,11]
#define BP_MAP_FLASH {0xC0, 0x0F, 0x00, 0x00, 0x00}
// Carry the agent's serial link (uart0): always refused, reported as mode "uart". [1,3]
#define BP_MAP_UART {0x0A, 0x00, 0x00, 0x00, 0x00}
// USB data lines and debug port: always refused.
#define BP_MAP_BLOCKED {0x00, 0x00, 0x00, 0x00, 0x00}
// Input only: outputs, PWM and I2C refused. [34,35,36,37,38,39]
#define BP_MAP_INPUT_ONLY {0x00, 0x00, 0x00, 0x00, 0xFC}
// No internal pull-up / pull-down.
#define BP_MAP_NO_PULL {0x00, 0x00, 0x00, 0x00, 0xFC}
// ADC capable.
#define BP_MAP_ADC {0x15, 0xF0, 0x00, 0x0E, 0x9F}
// Used by something on the board: left alone at start-up, usable on request.
#define BP_MAP_RESERVED {0x00, 0x00, 0x00, 0x00, 0x00}

// Messages.
#define BP_MSG_BAD_PIN "This GPIO number does not exist on the ESP32."
#define BP_MSG_FLASH "GPIO 6 to 11 are wired to the internal flash. Using them would crash the board."
#define BP_MSG_UART "GPIO 1 and 3 carry the serial link to the computer. Using them would cut the connection."
#define BP_MSG_BLOCKED "This pin is used by the USB connection or the debug probe. The agent leaves it alone."
#define BP_MSG_INPUT_ONLY "GPIO 34 to 39 are input only. They cannot drive a signal or be used as I2C lines."
#define BP_MSG_NOT_ADC_FMT "GPIO %d cannot measure voltage. Use an ADC pin, best GPIO 32 to 39."
