// Starter Arduino sketch for a scene. Uses BoardPilotProbe so Monitor can plot the values.

import type { BoardDef, PartDef, Scene } from './types';
import { boardPinFor, pinById } from './board';

const ident = (s: string) => s.replace(/[^A-Za-z0-9]/g, '_').toUpperCase();

export function generateSketch(scene: Scene, board: BoardDef, parts: Record<string, PartDef>): string {
  const includes = new Set<string>(['#include <Wire.h>', '#include <BoardPilotProbe.h>']);
  const globals: string[] = ['BoardPilotProbe probe(Serial);'];
  const defines: string[] = [];
  const setup: string[] = ['  Serial.begin(115200);', '  probe.begin(100);'];
  const loop: string[] = [];
  const libs = new Set<string>();
  let wireBegun = false;

  const gpio = (instId: string, pin: string) => {
    const bp = boardPinFor(scene, instId, pin);
    const p = bp ? pinById(board, bp) : undefined;
    return p?.gpio ?? null;
  };

  for (const inst of scene.parts) {
    const def = parts[inst.partId];
    if (!def) continue;
    const N = ident(inst.id);
    if (def.bus === 'i2c') {
      const sda = gpio(inst.id, 'SDA') ?? 21;
      const scl = gpio(inst.id, 'SCL') ?? 22;
      if (!wireBegun) {
        defines.push(`#define I2C_SDA ${sda}`, `#define I2C_SCL ${scl}`);
        setup.push('  Wire.begin(I2C_SDA, I2C_SCL);');
        wireBegun = true;
      }
    }
    switch (def.starterSketch) {
      case 'bme280':
        includes.add('#include <Adafruit_BME280.h>');
        libs.add('Adafruit BME280 Library');
        globals.push(`Adafruit_BME280 ${inst.id};`);
        setup.push(
          `  if (!${inst.id}.begin(0x76, &Wire) && !${inst.id}.begin(0x77, &Wire)) {`,
          `    Serial.println("BME280 not found. Run Debug > A sensor does not respond in BoardPilot.");`,
          '  }',
        );
        loop.push(
          `  probe.value("temperature", ${inst.id}.readTemperature(), I2C_SDA);`,
          `  probe.value("humidity", ${inst.id}.readHumidity(), I2C_SDA);`,
          `  probe.value("pressure", ${inst.id}.readPressure() / 100.0F, I2C_SDA);`,
        );
        break;
      case 'ssd1306':
        includes.add('#include <Adafruit_SSD1306.h>');
        libs.add('Adafruit SSD1306');
        globals.push(`Adafruit_SSD1306 ${inst.id}(128, 64, &Wire, -1);`);
        setup.push(`  ${inst.id}.begin(SSD1306_SWITCHCAPVCC, 0x3C);`, `  ${inst.id}.clearDisplay();`, `  ${inst.id}.display();`);
        break;
      case 'led': {
        const g = gpio(inst.id, 'A');
        if (g === null) break;
        defines.push(`#define ${N}_PIN ${g}`);
        setup.push(`  pinMode(${N}_PIN, OUTPUT);`);
        loop.push(`  digitalWrite(${N}_PIN, (millis() / 500) % 2);  // blink`);
        break;
      }
      case 'button': {
        const g = gpio(inst.id, '1');
        if (g === null) break;
        defines.push(`#define ${N}_PIN ${g}`);
        setup.push(`  pinMode(${N}_PIN, INPUT_PULLUP);  // pressed = LOW`);
        loop.push(`  probe.value("${inst.id}", digitalRead(${N}_PIN) == LOW ? 1 : 0, ${N}_PIN);`);
        break;
      }
      case 'pot': {
        const g = gpio(inst.id, 'OUT');
        if (g === null) break;
        defines.push(`#define ${N}_PIN ${g}`);
        loop.push(`  probe.value("${inst.id}", analogReadMilliVolts(${N}_PIN), ${N}_PIN);  // mV`);
        break;
      }
      case 'mpu6050':
        setup.push(`  Wire.beginTransmission(0x68); Wire.write(0x6B); Wire.write(0); Wire.endTransmission();  // wake up`);
        loop.push(
          `  Wire.beginTransmission(0x68); Wire.write(0x3B); Wire.endTransmission(false);`,
          `  Wire.requestFrom((uint8_t)0x68, (uint8_t)6);`,
          `  int16_t ax = (Wire.read() << 8) | Wire.read(); Wire.read(); Wire.read(); Wire.read(); Wire.read();`,
          `  probe.value("accel_x", ax / 16384.0);`,
        );
        break;
      case 'dht22': {
        const g = gpio(inst.id, 'DATA');
        if (g === null) break;
        includes.add('#include <DHT.h>');
        libs.add('DHT sensor library');
        defines.push(`#define ${N}_PIN ${g}`);
        globals.push(`DHT ${inst.id}(${N}_PIN, DHT22);`);
        setup.push(`  ${inst.id}.begin();`);
        loop.push(`  probe.value("dht_temperature", ${inst.id}.readTemperature(), ${N}_PIN);`, `  probe.value("dht_humidity", ${inst.id}.readHumidity(), ${N}_PIN);`);
        break;
      }
    }
  }

  return [
    `// Starter sketch generated by BoardPilot for ${board.name}.`,
    `// Libraries to install (Arduino Library Manager): BoardPilotProbe (firmware/probe)${[...libs].map((l) => `, ${l}`).join('')}`,
    '',
    ...includes,
    '',
    ...defines,
    '',
    ...globals,
    '',
    'void setup() {',
    ...setup,
    '}',
    '',
    'void loop() {',
    ...loop,
    '  probe.loop();  // sends the values and memory info to BoardPilot Monitor',
    '  delay(50);',
    '}',
    '',
  ].join('\n');
}
